<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>esup-transferts</artifactId>
		<groupId>org.esupportail.transferts</groupId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<groupId>org.esupportail.transferts</groupId>
	<artifactId>esup-transferts-domain-services</artifactId>
	<description>Domain Interface and Impl</description>
	<dependencies>
		<dependency>
			<groupId>org.esupportail.transferts</groupId>
			<artifactId>esup-transferts-domain-beans</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.esupportail</groupId>
			<artifactId>esup-commons2-auth</artifactId>
			<version>${esupcommons.version}</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.esupportail.transferts</groupId>
			<artifactId>esup-transferts-dao</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.esupportail.transferts</groupId>
			<artifactId>esup-transferts-utils</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.esupportail</groupId>
			<artifactId>esup-commons2-jsf2-exception</artifactId>
			<version>${esupcommons.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.esupportail</groupId>
			<artifactId>esup-commons2-ws-cxf</artifactId>
			<version>${esupcommons.version}</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.esupportail</groupId>
			<artifactId>esup-commons2-rs-cxf</artifactId>
			<version>${esupcommons.version}</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.esupportail</groupId>
			<artifactId>esup-commons2-ldap</artifactId>
			<version>${esupcommons.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>spring-tx</artifactId>
					<groupId>org.springframework</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.googlecode.ehcache-spring-annotations</groupId>
			<artifactId>ehcache-spring-annotations</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<version>2.3.3</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>com.sun.org.apache.xml.internal</groupId>
			<artifactId>resolver</artifactId>
			<version>20050927</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign.form</groupId>
			<artifactId>feign-form</artifactId>
			<version>3.8.0</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-okhttp</artifactId>
			<version>12.3</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-slf4j</artifactId>
			<version>12.3</version>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>pegase</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<configuration>
							<excludes>
								<exclude>org/esupportail/transferts/domain/DomainServiceApogeeImpl.java</exclude>
							</excludes>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
