<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>esup-transferts</artifactId>
		<groupId>org.esupportail.transferts</groupId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>esup-transferts-utils</artifactId>
	<description>couche utilitaire</description>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>properties-maven-plugin</artifactId>
				<version>1.0.0</version>
				<executions>
					<execution>
						<phase>initialize</phase>
						<goals>
							<goal>read-project-properties</goal>
						</goals>
						<configuration>
							<files>
								<file>${basedir}/../esup-transferts-web-jsf-servlet/src/main/resources/properties/config.properties</file>
							</files>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.esupportail.transferts</groupId>
			<artifactId>esup-transferts-domain-beans</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.esupportail</groupId>
			<artifactId>esup-commons2-jsf2-exception</artifactId>
			<version>${esupcommons.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>local</groupId>
			<artifactId>ws-mds-beans</artifactId>
			<version>1.0.0</version>
			<scope>system</scope>
			<systemPath>${basedir}/src/main/beans/ws-mds-domain-beans-1.0.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>local</groupId>
			<artifactId>ws-mds-ws</artifactId>
			<version>1.0.0</version>
			<scope>system</scope>
			<systemPath>${basedir}/src/main/beans/ws-mds-domain-services-1.0.jar
			</systemPath>
		</dependency>
		<dependency>
			<groupId>org.apache.cxf</groupId>
			<artifactId>cxf-rt-frontend-jaxws</artifactId>
			<version>2.4.2</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<version>2.3.1</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-core</artifactId>
			<version>12.3</version>
		</dependency>
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-jackson</artifactId>
			<version>12.3</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.26</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>apogee</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>pegase</id>
		</profile>
	</profiles>
</project>
